### PR TITLE
Logging file handler fix

### LINKED ISSUE #132: Update RotatingFileHandler in Python code to stop permissions error when calling it LOTS
#### Description:

When running processes that call BHoM decorated methods LOTS, the file handler writing the logs can get a bit confused. This can be fixed by changing the way we're calling the logger to hopefully save any behind-the-scenes breakages which stop BHoM-UI exposed processed from running fully.

#### Steps to reproduce:

Inconsistent, though bound to happen when you least expect/want it to.

#### Expected behaviour:

No hanging processes. This may be a good opportunity to add a timeout to Python called methods that raise an error and return a null if the processes takes longer than a certain amount of time.

### PR DESCRIPTION
**Pull request by tg359**
### Issues addressed by this PR

Closes #132 

Logging *should* no longer get confused and try to rewrite to a blocked file. Additionally, the method for tagging the logs now removes the config.ini to save on time spent opening/closing files with each call.

Also updates a few of the Compute methods which call to Python to convert files so that they use the new method of running an external *.py file instead of having the Python command strings within the C# methods - to save on headaches for people trying to debug (the *.py files can then be debugged outside of C# if necessary).

### CODE REVIEW

File: LadybugTools_Engine/Compute/HBJSONtoGEM.cs [hunk 1]
```diff
@@ -51,26 +49,21 @@ public static string HBJSONtoGEM(string hbjson)
 
             PythonEnvironment env = InstallPythonEnv_LBT(true);
 
-            string hbjsonFile = System.IO.Path.GetFullPath(hbjson);
-            string outputDirectory = System.IO.Path.GetDirectoryName(hbjsonFile);
-            string fileName = System.IO.Path.GetFileNameWithoutExtension(hbjsonFile);
+            hbjson = System.IO.Path.GetFullPath(hbjson);
+            string gemFile = System.IO.Path.ChangeExtension(hbjson, ".gem");
```
Comment (Tom-Kingstone) [inline LadybugTools_Engine/Compute/HBJSONtoGEM.cs:53]: Please handle when hbjson is null or file not existing

**Review by Tom-Kingstone — CHANGES_REQUESTED** [review]
Just the one request for now :)

**Comment by Tom-Kingstone** [comment]
@BHoMBot check core
@BHoMBot check compliance

File: LadybugTools_Engine/Python/src/ladybugtools_toolkit/bhom/__init__.py [hunk 2]
```diff
@@ -1,6 +1,22 @@
...
+from win32api import HIWORD, LOWORD, GetFileVersionInfo
+
+BHOM_ASSEMBLIES_DIRECTORY = Path("C:/ProgramData/BHoM/Assemblies")
+BHOM_DIRECTORY = Path("C:/ProgramData/BHoM")
+BHOM_LOG_FOLDER = Path("C:/ProgramData/BHoM/Logs")
+
+PYTHON_CODE_DIRECTORY = Path("C:/ProgramData/BHoM/Extensions/PythonCode")
+PYTHON_ENVIRONMENTS_DIRECTORY = Path(
+    "C:/ProgramData/BHoM/Extensions/PythonEnvironments"
+)
```
Comment (FraserGreenroyd) [inline LadybugTools_Engine/Python/src/ladybugtools_toolkit/bhom/__init__.py:14]: @Tom-Kingstone can you raise an issue about changing these from `C:` to a generic `ProgramData`. In C#, this can be done by using `System.Environment.GetFolderPath(System.Environment.SpecialFolder.CommonApplicationData)` where `System.Environment.GetFolderPath()` method gets the folder path for a given folder and `System.Environment.SpecialFolder.CommonApplicationData` is the enum for determining `ProgramData` over `AppData` or other common folders within the system.

I'd hope Python has a similar ability 😄 

FYI @tg359

**Review by FraserGreenroyd — APPROVED** [review]
This all looks good on code review @tg359 happy with the tests running as usual. Have made a comment for a change in another PR for @Tom-Kingstone to pick up but otherwise, let's get this merged and out of the way 😄

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: unit-tests, ready-to-merge, installer
